apiVersion: v1
kind: Secret
metadata:
  name: banking-secrets
  namespace: banking-ledger
type: Opaque
data:
  # Base64 for 'banking123'
  DB_PASSWORD: YmFua2luZzEyMw==
  RABBITMQ_PASSWORD: YmFua2luZzEyMw==
